# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.11-slim
WORKDIR /app
# Install dependencies
RUN pip install --no-cache-dir "mcp[cli]>=1.6.0" "websocket>=0.2.1" "websocket-client>=1.8.0"
# Copy server source
COPY server.py .

# Default command to run MCP server
CMD ["python", "server.py"]
